services:
  - type: web
    name: telegram-social-video-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: 7767921269:AAFxOOGInLTmGcih2ERWeZubpDeHyBfzp8c
